version: "3.8"

x-app: &app
  build:
    context: .
    dockerfile: Dockerfile
  env_file:
    - .env
  environment:
    DATABASE_URL: "postgres://postgres:postgres@db:5432/postgres"


services:
  app:
    <<: *app
    container_name: app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    command: python manage.py runserver 0.0.0.0:8000

  migrate:
    <<: *app
    container_name: migrate
    command: python manage.py migrate
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 1s

volumes:
  postgres_data:
